version: '3.8'

services:
  app:
    container_name: aiogram-dialog-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8005:8080"  # На хосте 8005, в докере 8080,
    depends_on:
      - redis
    environment:
      - BOT_REDIS_URL=redis://redis:6379/0


  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "45580:6379" # На хосте 45580, в докере 6379
