services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    security_opt:
      - no-new-privileges:true
    environment:
        - BOT_TOKEN=${BOT_TOKEN}
        - BOT_ADMIN_ID=${BOT_ADMIN_ID}
        - BOT_GRADIO_URL=${BOT_GRADIO_URL}

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    security_opt:
      - no-new-privileges:true