version: '3.8'

services:
#  app:
#    container_name: aiogram-dialog-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - "8005:8080"  # На хосте 8005, в докере 8080,
#    depends_on:
#      - redis
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6363:6379" # На хосте 6363, в докере 6379
